image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      npm install
      npm i ts-node -g
    command: ts-node src/index.js
ports:
  - port: 3000
    onOpen: open-browser
  - port: 5900
    onOpen: ignore